### ISSUE TITLE
Wrong atom feed URL.

### ISSUE THREAD

**Issue by linyiru** [rickhw/rickhw.github.io#1]
It should be `/atom.xml` instead of `true` in your HTML head. 

I guessed there is typo in your configuration of Hexo. 

```
feed:
  type: atom
  path: atom.xml
  limit: 10
```

https://github.com/rickhw/rickhw.github.io/blob/71b7d2b45a6dba27db3b87f5dcef14461bbcecb0/index.html#L22
